---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cos
# description will be included in the image's metadata
description: Custom fedora atomic image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/markupstart/SwayOSD/repo/fedora-%OS_VERSION%/markupstart-SwayOSD-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/markupstart/xwayland-satellite/repo/fedora-%OS_VERSION%/markupstart-xwayland-satellite-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-%OS_VERSION%/yalter-niri-git-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - fish
      - zoxide
      - eza
      - tmux
      - neovim
      - htop
      - fzf
      - bat
      - niri
      - git-delta
      - syncthing
      - polkit-kde
      - distrobox
      - fastfetch
      - libinput-utils
      - fuzzel
      - waybar
      - kanshi
      - hyprlock
      - hypridle
      - gamescope
      - cascadia-code-nf-fonts
#    remove:

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
      repo-name: flathub-beta
      repo-title: "Flathub (beta)"
      install:
        - com.yubico.yubioath
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.discordapp.Discord
        - com.valvesoftware.Steam
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /


  - type: signing # this sets up the proper policy & signing files for signed images to work fully

